version: '3.1'

services:

  db:
    build: 
      context: .
      dockerfile: Dockerfile.mysql
    image: measurements-db
    restart: always
    ports:
      - 3306:3306
      - 33060:33060
    expose: 
      - 3306
      - 33060
    env_file:
      - .env

  grafana:
    image: grafana/grafana
    restart: always
    depends_on: 
      - db
    ports:
      - 3000:3000

  measure:
    build: .
    image: measure
    restart: always
    depends_on: 
      - db